### ISSUE TITLE
Create gRPC infrastructure in Rust

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/ArunaServer#9]
### Overview

Create the necessary Rust services and gRPC backbones to handle the associated requests. The actual CRUD methods that are part of each service are tracked in: #10

### Tasks

- [x] Overall infrastructure / gRPC server
- [x] AuthService implementation
- [x] CollectionService implementation
- [x] ObjectService implementation
- [x] ObjectGroupService implementation

### Discussions

**Comment by St4NNi** [comment]
Fixed in #34
